spring:
  application:
    name: events-app-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/events_app_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mustache:
    check-template-location: false
  thymeleaf:
    check-template-location: false


server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  expiration: 1800000
  secret: 3167ceee9cb36d05a553fd48752e077e8e2c7edef0c046f7bc7a38678f7bd8da
  refresh:
    expiration: 604800000

cloudinary:
  cloud-name: dn0akydmv
  api-key: 883779744122919
  api-secret: 2q8MUhDG4sUjtN47HZS823Zxjko